package com.blazartech.droolsdemo.order;

global org.slf4j.Logger logger;

dialect 'mvel';
dialect 'java';

rule "sum and Apply 10% discount to orders over US$ 100,00"
when
    $order : Order()
    $total : Number(  ) 
             from accumulate( OrderItem( order == $order, $value : value ),
                              init( double total = 0; ),
                              action( total += $value; ),
                              reverse( total -= $value; ),
                              result( total ) )
then
    $order.setTotal($total);

    if ($total > 100) {
        // apply discount to $order
        logger.info("applying discount");
        $order.setDiscountApplied(true);
        $order.setTotal($total * .9);
    }
end
